### ISSUE TITLE
Panel & Wings on Same Server

### ISSUE THREAD

**Issue by kadenscott** [EdyTheCow/pterodactyl-docker#11]
From the README: 

> It's not recommended to run panel and wings on the same server! While this may be possible, it may cause issues. This guide assumes panel and wings are running on two separate servers.

I was wondering why this disclaimer is here? I am interested in running a setup where panel and wings are running on the same box. What issues should I expect to run when attempting this setup?

**Comment by EdyTheCow** [comment]
Because wings and panel were never designed to run together on the same server. I haven't specifically tested Pterodactyl v1 for running both on the same box. So I can't really say what issues you may encounter. I am currently running two boxes with wings and a cheap 4 dollar VPS running panel. Panel doesn't need a lot of resources at all, in case you'll go with running panel in VPS solution. Hetzner provides one of the cheapest VPS for the amount of resources they provide.

**Comment by kadenscott** [comment]
Thanks for the clarification, @EdyTheCow. I'm a newcomer to the Pterodactyl panel and I realize I was attempting to shoehorn it into something it wasn't suited for. I ran into a few pain points and decided it wasn't worth it to continue. I'll be looking into a multi-server setup now, cheers 😄

(Sidenote: this repository is very useful, thanks for creating it 👍)
