### ISSUE TITLE
Error completing LetsEncrypt Challenge

### ISSUE THREAD

**Issue by Fireant456** [EdyTheCow/pterodactyl-docker#12]
I keep running into this issue and I am not sure what is causing it.
![image](https://user-images.githubusercontent.com/1479965/119064516-1f3e9380-b9a1-11eb-8ea9-38f13817c09c.png)

**Comment by Fireant456** [comment]
Moreso the issue seems to be with Pterodactyl's panel. Whenever I try connecting either through Cloudflare or directly I get a "Bad Gateway" error. Any ideas?

**Comment by EdyTheCow** [comment]
Did you by any chance uncomment the "LE_EMAIL" line here https://github.com/EdyTheCow/pterodactyl-docker/blob/master/panel/compose/docker-compose.yml#L17 ? It looks like panel is looking for certificate, if you're using traefik that line should be commented out since traefik is taking care of certificates.
