### ISSUE TITLE
Mobile?

### ISSUE THREAD

**Issue by TekExplorer** [EdyTheCow/pterodactyl-docker#3]
how would i add the mobile addon to this setup? running the commands through docker exec broke my install...

**Comment by EdyTheCow** [comment]
Could you link me the mobile addon? I thought it worked out of the box when using pterodactyl mobile app.

**Comment by TekExplorer** [comment]
Pterodactyl.cloud

**Comment by EdyTheCow** [comment]
It looks like it requires editing of the Dockerfile itself in order to add that. I may add an optional script with a variable something like **MOBILE_SUPPORT=**.  If set to true, it would install the required packages.

**Comment by TekExplorer** [comment]
perhaps. couldnt you use FROM and make your own dockerfile that takes the existing image and adds that one bit? or is there a better solution? and while im at it, how would i install addons? themes i think just go into themes folder but isnt there a command to run?

also, thanks for making this guide, its way simpler than what i stumbled onto (this was before you fixed it :/)

**Comment by EdyTheCow** [comment]
Yes, FROM would be the simplest way. However, I still wanna make this an option to keep the setup more flexible. As for addons and themes, it's tricky. In theory you could create a volume for the whole panel and apply themes and addons, then run the commands inside the container. However, if certain addon requires additional packages that wouldn't work since installed packages would be deleted when container is recreated. I don't plan on adding support of themes and addons, it would require a complex solution since each addon's requirements are different. Since most addons are paid, I wouldn't be able to include them in the image either. 
The main goal of this guide was to simplify the setup for myself since there's basically no information for setting this up using containers and traefik. I'm glad the guide helped you :)

**Comment by TekExplorer** [comment]
cool, well i await your solution.

hopefully it meshes well with my setup, as i actually got it working before you had a usable guide (if you remember from my other issues). it is, however, helping someone else right now! way simpler than mine :/

i over-complicated the heck out of mine, so i wont touch it until the mobile addon gets the spotlight :)

ps. is addon not a word? tf google?

**Comment by TekExplorer** [comment]
i just built an image with the mobile addon built in. its available on both my github and docker hub by the same name. i need to make sure it works, and i have no idea how to make it only apply if an env variable (MOBILE_ADDON=true) is applied. feel free to suggest changes! (i cant believe ive done this successfully holy crap)

**Comment by TekExplorer** [comment]
Okay, so I'm doing something wrong. I have it working on first boot, but not for existing setup... Im still learning about docker, what do you suggest?

**Comment by EdyTheCow** [comment]
It seems like mobile addon is no longer supported in v1.x so closing this until mobile addon is updated.
