### ISSUE TITLE
SSL Certificates not being Generated

### ISSUE THREAD

**Issue by TekExplorer** [EdyTheCow/pterodactyl-docker#4]
so im helping someone install their panel (and your instructions worked better than when i was doing it) with your instructions, and everything seems to work... except for certificates. the site works (though you have to specifically go to https and i recommend adding a redirect to your compose or toml) but give me the invalid certificate thing. traefik default cert, and im getting no useful info. the daemon wont work with the panel because of it. otherwise, everything else is fine...

**Comment by EdyTheCow** [comment]
> so im helping someone install their panel (and your instructions worked better than when i was doing it) with your instructions, and everything seems to work... except for certificates. the site works (though you have to specifically go to https and i recommend adding a redirect to your compose or toml) but give me the invalid certificate thing. traefik default cert, and im getting no useful info. the daemon wont work with the panel because of it. otherwise, everything else is fine...

Since this setup is using Cloudflare to do DNS challenges for generating certificates I just use Cloudflare's HTTPS redirect option which can be found under security section I believe. I also haven't specified this in the guide, but make sure to set your "encryption mode" to **strict**. In most cases it may be set to **flexible** which will cause issues. Traefik doesn't generate the certificates anywhere on host, so you won't be able to actually see the certificate files unless you go digging inside the traefik container. Which you shouldn't need to since traefik handles all of certificate related stuff.

**Comment by TekExplorer** [comment]
i didnt consider encryption mode, thanks, i will suggest he try this

**Comment by TekExplorer** [comment]
also, perhaps add this info to the instructions as well. should make things simpler :)

**Comment by EdyTheCow** [comment]
> also, perhaps add this info to the instructions as well. should make things simpler :)

Will do, I overlooked that part when creating the guide

**Comment by TekExplorer** [comment]
you should also make sure it mentions making cnames panel and node, and if they need to be proxied = true
